Add basic development instructions to readme
opennem/opennem-fe pull request #63
Opened 2021-11-17 10:38 UTC by lb-

Hi, I am hoping to help out with this project here and there if I have some time. Not 100% sure if this sub project accepts PRs but I thought I would give it a go.

This PR introduces some basic 'development' instructions, I was not sure what version of Node is preferred so I left that out, it seems to work fine for me on Node 14.

Please let me know if this is helpful or if only the Python (backend) repo accepts PRs.

2021-11-19 23:55 UTC, chienleng commented
hey @lb- , yep it does. it's just not tidied up properly as it is always in a state of active dev. Node 14 is preferred atm.

2021-11-19 23:58 UTC, chienleng requested changes

2021-11-19 23:58 UTC, chienleng commented on README.md
> +## Development
Add a top and bottom horizontal rule for the Development section. To make it more readable.

2021-11-30 00:37 UTC, chienleng approved these changes

2021-11-30 00:37 UTC, merged

2021-12-01 22:23 UTC, lb- commented
Thanks.